/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import agentes.*;
import conceptos.Libro;
import conceptos.Tesis;
import java.util.ArrayList;

/**
 *
 * @author Susana
 */
public class FrmMainMenu extends javax.swing.JFrame {

    public static ArrayList<Libro> arrLibros = new ArrayList();
    public static ArrayList<Tesis> arrTesis = new ArrayList();
    
    public FrmMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AgentManager.creaAgente("Bibliotecario", "agentes.Bibliotecario", null);
        AgentManager.creaAgente("Almacenista", "agentes.Almacenista", null);
        AgentManager.creaAgente("Recepcionista", "agentes.Recepcionista", null);
        
        arrLibros = createDB.readFromFileLibros();
        arrTesis = createDB.readFromFileTesis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrestamos = new javax.swing.JPanel();
        btnSolicitarLibro = new javax.swing.JButton();
        btnSolicitarTesis = new javax.swing.JButton();
        pnlDevoluciones = new javax.swing.JPanel();
        btnDevolverLibro = new javax.swing.JButton();
        btnDevolverTesis = new javax.swing.JButton();
        btnListaTesis = new javax.swing.JButton();
        btnListaLibros = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(724, 409));
        setMinimumSize(new java.awt.Dimension(724, 409));
        setPreferredSize(new java.awt.Dimension(724, 409));
        getContentPane().setLayout(null);

        pnlPrestamos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitudes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnSolicitarLibro.setText("Solicitar Libro");
        btnSolicitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarLibroActionPerformed(evt);
            }
        });

        btnSolicitarTesis.setText("Solicitar Tesis");
        btnSolicitarTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarTesisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrestamosLayout = new javax.swing.GroupLayout(pnlPrestamos);
        pnlPrestamos.setLayout(pnlPrestamosLayout);
        pnlPrestamosLayout.setHorizontalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSolicitarTesis)
                    .addComponent(btnSolicitarLibro))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnlPrestamosLayout.setVerticalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnSolicitarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnSolicitarTesis)
                .addGap(23, 23, 23))
        );

        getContentPane().add(pnlPrestamos);
        pnlPrestamos.setBounds(150, 30, 180, 160);
        pnlPrestamos.getAccessibleContext().setAccessibleName("Préstamos");

        pnlDevoluciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Devoluciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnDevolverLibro.setText("Devolver Libro");
        btnDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLibroActionPerformed(evt);
            }
        });

        btnDevolverTesis.setText("Devolver Tesis");
        btnDevolverTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverTesisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDevolucionesLayout = new javax.swing.GroupLayout(pnlDevoluciones);
        pnlDevoluciones.setLayout(pnlDevolucionesLayout);
        pnlDevolucionesLayout.setHorizontalGroup(
            pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDevolucionesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolverTesis)
                    .addComponent(btnDevolverLibro))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlDevolucionesLayout.setVerticalGroup(
            pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDevolucionesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDevolverLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnDevolverTesis)
                .addGap(24, 24, 24))
        );

        getContentPane().add(pnlDevoluciones);
        pnlDevoluciones.setBounds(380, 30, 190, 160);

        btnListaTesis.setText("Tesis");
        btnListaTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaTesisActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaTesis);
        btnListaTesis.setBounds(230, 210, 70, 23);

        btnListaLibros.setText("Libros");
        btnListaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaLibrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaLibros);
        btnListaLibros.setBounds(150, 210, 73, 23);

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Título", "Ejemplares"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLista);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 240, 452, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/library.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 728, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    
    private void btnSolicitarTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarTesisActionPerformed
        RecepcionistaTickerBehaviour.content = "Solicitar Tesis";
    }//GEN-LAST:event_btnSolicitarTesisActionPerformed

    private void btnDevolverTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverTesisActionPerformed
        RecepcionistaTickerBehaviour.content = "Devolver Tesis";
    }//GEN-LAST:event_btnDevolverTesisActionPerformed

    private void btnSolicitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarLibroActionPerformed
        RecepcionistaTickerBehaviour.content = "Solicitar Libro";
    }//GEN-LAST:event_btnSolicitarLibroActionPerformed

    private void btnDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibroActionPerformed
        RecepcionistaTickerBehaviour.content = "Devolver Tesis";
    }//GEN-LAST:event_btnDevolverLibroActionPerformed

    private void btnListaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaLibrosActionPerformed
        createDB.printArrLibros(arrLibros, tblLista);
    }//GEN-LAST:event_btnListaLibrosActionPerformed

    private void btnListaTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaTesisActionPerformed
        createDB.printArrTesis(arrTesis, tblLista);
    }//GEN-LAST:event_btnListaTesisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverLibro;
    private javax.swing.JButton btnDevolverTesis;
    private javax.swing.JButton btnListaLibros;
    private javax.swing.JButton btnListaTesis;
    private javax.swing.JButton btnSolicitarLibro;
    private javax.swing.JButton btnSolicitarTesis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlDevoluciones;
    private javax.swing.JPanel pnlPrestamos;
    private javax.swing.JTable tblLista;
    // End of variables declaration//GEN-END:variables
}
