/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import agentes.*;

/**
 *
 * @author Susana
 */
public class FrmMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainMenu
     */
    public FrmMainMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        AgentManager.creaAgente("Bibliotecario", "agentes.Bibliotecario", null);
        AgentManager.creaAgente("Almacenista", "agentes.Almacenista", null);
        AgentManager.creaAgente("Recepcionista", "agentes.Recepcionista", null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarUsuario = new javax.swing.JButton();
        pnlPrestamos = new javax.swing.JPanel();
        btnSolicitarLibro = new javax.swing.JButton();
        btnSolicitarTesis = new javax.swing.JButton();
        pnlDevoluciones = new javax.swing.JPanel();
        btnDevolverLibro = new javax.swing.JButton();
        btnDevolverTesis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(724, 409));
        setMinimumSize(new java.awt.Dimension(724, 409));
        setPreferredSize(new java.awt.Dimension(724, 409));
        getContentPane().setLayout(null);

        btnRegistrarUsuario.setBackground(new java.awt.Color(102, 153, 0));
        btnRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        btnRegistrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarUsuario.setLabel("Registrar Usuario");
        btnRegistrarUsuario.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnRegistrarUsuario.setMaximumSize(new java.awt.Dimension(100, 200));
        btnRegistrarUsuario.setMinimumSize(new java.awt.Dimension(100, 200));
        btnRegistrarUsuario.setPreferredSize(new java.awt.Dimension(100, 200));
        btnRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUsuario);
        btnRegistrarUsuario.setBounds(60, 50, 190, 60);

        pnlPrestamos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Solicitudes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnSolicitarLibro.setText("Solicitar Libro");
        btnSolicitarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarLibroActionPerformed(evt);
            }
        });

        btnSolicitarTesis.setText("Solicitar Tesis");
        btnSolicitarTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarTesisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrestamosLayout = new javax.swing.GroupLayout(pnlPrestamos);
        pnlPrestamos.setLayout(pnlPrestamosLayout);
        pnlPrestamosLayout.setHorizontalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSolicitarLibro)
                    .addComponent(btnSolicitarTesis))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        pnlPrestamosLayout.setVerticalGroup(
            pnlPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnSolicitarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnSolicitarTesis)
                .addGap(59, 59, 59))
        );

        getContentPane().add(pnlPrestamos);
        pnlPrestamos.setBounds(60, 140, 232, 216);
        pnlPrestamos.getAccessibleContext().setAccessibleName("Préstamos");

        pnlDevoluciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Devoluciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        btnDevolverLibro.setText("Devolver Libro");
        btnDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLibroActionPerformed(evt);
            }
        });

        btnDevolverTesis.setText("Devolver Tesis");
        btnDevolverTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverTesisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDevolucionesLayout = new javax.swing.GroupLayout(pnlDevoluciones);
        pnlDevoluciones.setLayout(pnlDevolucionesLayout);
        pnlDevolucionesLayout.setHorizontalGroup(
            pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDevolucionesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDevolverTesis)
                    .addComponent(btnDevolverLibro))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlDevolucionesLayout.setVerticalGroup(
            pnlDevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDevolucionesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnDevolverLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnDevolverTesis)
                .addGap(51, 51, 51))
        );

        getContentPane().add(pnlDevoluciones);
        pnlDevoluciones.setBounds(380, 140, 234, 216);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/library.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 728, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    
    private void btnSolicitarTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarTesisActionPerformed
        RecepcionistaTickerBehaviour.content = "Solicitar Tesis";
    }//GEN-LAST:event_btnSolicitarTesisActionPerformed

    private void btnDevolverTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverTesisActionPerformed
        RecepcionistaTickerBehaviour.content = "Devolver Tesis";
    }//GEN-LAST:event_btnDevolverTesisActionPerformed

    private void btnRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarUsuarioActionPerformed

    private void btnSolicitarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarLibroActionPerformed
        RecepcionistaTickerBehaviour.content = "Solicitar Libro";
    }//GEN-LAST:event_btnSolicitarLibroActionPerformed

    private void btnDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibroActionPerformed
        RecepcionistaTickerBehaviour.content = "Devolver Tesis";
    }//GEN-LAST:event_btnDevolverLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverLibro;
    private javax.swing.JButton btnDevolverTesis;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnSolicitarLibro;
    private javax.swing.JButton btnSolicitarTesis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlDevoluciones;
    private javax.swing.JPanel pnlPrestamos;
    // End of variables declaration//GEN-END:variables
}
